name: Build OktaPS module
on: 
  push:
    branches:
    - main
  workflow_dispatch

jobs:
  build:
    name: Build module
    runs-on:
      - self-hosted
      - commercial
      - builder
    container:
      image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install InvokeBuild module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild

      - name: Perform an Invoke-Build from the command line
        shell: pwsh
        run: Invoke-Build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release

      - name: Publish to Nexus
        shell: pwsh
        run: Invoke-Build Publish -NugetServer ${{ secrets.NEXUS_URL }} -NugetApiKey ${{ secrets.NEXUS_APIKEY }}