name: Build OktaPS module
on: 
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    name: Build module
    runs-on:
      - self-hosted
      - commercial
      - builder
    container:
      image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install InvokeBuild module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.12.0'

      - name: Determine Version
        id:   gitversion # id to later be referenced
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Perform an Invoke-Build from the command line
        shell: pwsh
        run: Invoke-Build -SemVer ${{ steps.gitversion.outputs.MajorMinorPatch }}}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release

      - name: Publish to Nexus
        shell: pwsh
        run: Invoke-Build Publish -NugetServer ${{ secrets.NEXUS_URL }} -NugetApiKey ${{ secrets.NEXUS_APIKEY }}