name: Build OktaPS module
on: 
  workflow_dispatch

jobs:
  build:
    name: Build module
    runs-on: [self-hosted, linux]
    container:
      image: docker pull mcr.microsoft.com/powershell:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install InvokeBuild module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild

      - name: Perform an Invoke-Build from the command line
        shell: pwsh
        run: Invoke-Build