name: Build OktaPS module
on: 
  workflow_dispatch

jobs:
  build-oktaps:
    name: Build OktaPS Module
    runs-on: 
      - self-hosted
      - commercial
      - builder
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install InvokeBuild PowerShell module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild

      - name: Perform an Invoke-Build from the command line
        shell: pwsh
        run: Invoke-Build